/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.sql.ResultSet;
import java.sql.SQLException;
import static view.AcessoBancoDados.nome;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;

/**
 *
 * @author Samuelson
 */
public class Gelaflix extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroCliente
     */
    public static AcessoBD acessoBD;
    public static ResultSet rs = null;
    public static String pedidoSQL1;
    public static String pedidoSQL2;
    public int userId;
    String tituloOriginal = null, tituloPortugues = null, classificacao = null, sinopse = null, duracao = null;
    boolean comparator = false;
    
    public Gelaflix(int userId) {
        initComponents();
        pedidoSQL1 = "SELECT nome FROM usuario where codigo = "+userId;
        System.out.println(pedidoSQL1);
        acessoBD = new AcessoBD();
        acessoBD.conecta();
        acessoBD.executa(pedidoSQL1);
        rs = acessoBD.consulta(pedidoSQL1);
        try{
            while(rs.next()){
                welcomeText.setText("Seja bem vindo(a), "+(nome = rs.getString("nome")));}
        }
        catch(SQLException e){
            System.out.println("Exceção: " + e.toString());
        }
        acessoBD.fechaConexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Filme5 = new javax.swing.JButton();
        Filme3 = new javax.swing.JButton();
        Filme2 = new javax.swing.JButton();
        Filme4 = new javax.swing.JButton();
        Filme1 = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        welcomeText = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Cliente");
        setForeground(java.awt.Color.white);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(253, 41, 123));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(253, 41, 123));
        jLabel4.setText("Gelaflix");

        Filme5.setBackground(new java.awt.Color(255, 255, 255));
        Filme5.setText("Filme 5");
        Filme5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Filme5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filme5ActionPerformed(evt);
            }
        });

        Filme3.setBackground(new java.awt.Color(255, 255, 255));
        Filme3.setText("Filme3");
        Filme3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filme3ActionPerformed(evt);
            }
        });

        Filme2.setBackground(new java.awt.Color(255, 255, 255));
        Filme2.setText("Filme2");
        Filme2.setToolTipText("");
        Filme2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filme2ActionPerformed(evt);
            }
        });

        Filme4.setBackground(new java.awt.Color(255, 255, 255));
        Filme4.setText("Filme4");
        Filme4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filme4ActionPerformed(evt);
            }
        });

        Filme1.setBackground(new java.awt.Color(255, 255, 255));
        Filme1.setText("Filme1");
        Filme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Filme1ActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(250, 40, 120));
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Desconectar");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        welcomeText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 88, 100));
        welcomeText.setText("Bem vindo");

        jToggleButton1.setBackground(new java.awt.Color(255, 88, 100));
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Sair");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(263, 263, 263))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Filme1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Filme2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Filme3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Filme4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(Filme5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(welcomeText)))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Filme1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Filme2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Filme3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Filme4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Filme5, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(welcomeText)
                    .addComponent(jToggleButton1))
                .addContainerGap())
        );

        Filme5.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Filme5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filme5ActionPerformed
        int ano = 0, cod = 5;
            pedidoSQL1 = "SELECT * FROM filme WHERE codigo = '"+cod+"'";
            acessoBD = new AcessoBD();
            acessoBD.conecta();
            rs = acessoBD.consulta(pedidoSQL1);
            
            try{
                while(rs.next()){
                System.out.println("Procurando dados");
                tituloOriginal = rs.getString("tituloOriginal");
                tituloPortugues = rs.getString("tituloPortugues");
                classificacao = rs.getString("classificacao");
                sinopse = rs.getString("sinopse");
                duracao = rs.getString("duracao");
                ano = Integer.parseInt(rs.getString("ano"));
                System.out.println("tituloOriginal: " + tituloOriginal);
                System.out.println("tituloPortugues: " + tituloPortugues);
                System.out.println("classificacao: " + classificacao);
                System.out.println("sinopse: " + sinopse);
                System.out.println("duracao: " + duracao);
                System.out.println("ano: " + ano);
                comparator = true;}
            }
            catch(SQLException e){
                System.out.println("Exceção: " + e.toString());
            }
            if(comparator == true){
                new Filme(tituloOriginal, tituloPortugues, classificacao, sinopse, duracao, ano).setVisible(true);
                comparator = false;
            }else{
                System.out.println("Nenhum dado foi encontrado");
            }
            acessoBD.fechaConexao();
    }//GEN-LAST:event_Filme5ActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaLoginModal(this, false).setVisible(true);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void Filme3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filme3ActionPerformed
        int ano = 0, cod = 3;
            pedidoSQL1 = "SELECT * FROM filme WHERE codigo = '"+cod+"'";
            acessoBD = new AcessoBD();
            acessoBD.conecta();
            rs = acessoBD.consulta(pedidoSQL1);
            
            try{
                while(rs.next()){
                tituloOriginal = rs.getString("tituloOriginal");
                tituloPortugues = rs.getString("tituloPortugues");
                classificacao = rs.getString("classificacao");
                sinopse = rs.getString("sinopse");
                duracao = rs.getString("duracao");
                ano = Integer.parseInt(rs.getString("ano"));
                System.out.println("tituloOriginal: " + tituloOriginal);
                System.out.println("tituloPortugues: " + tituloPortugues);
                System.out.println("classificacao: " + classificacao);
                System.out.println("sinopse: " + sinopse);
                System.out.println("duracao: " + duracao);
                System.out.println("ano: " + ano);
                comparator = true;}
            }
            catch(SQLException e){
                System.out.println("Exceção: " + e.toString());
            }
            if(comparator == true){
                new Filme(tituloOriginal, tituloPortugues, classificacao, sinopse, duracao, ano).setVisible(true);
                comparator = false;
            }else{
                System.out.println("Nenhum dado foi encontrado");
            }
            acessoBD.fechaConexao();
    }//GEN-LAST:event_Filme3ActionPerformed

    private void Filme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filme1ActionPerformed
        // TODO add your handling code here:
        int ano = 0, cod = 1;
            pedidoSQL1 = "SELECT * FROM filme WHERE codigo = '"+cod+"'";
            acessoBD = new AcessoBD();
            acessoBD.conecta();
            rs = acessoBD.consulta(pedidoSQL1);
            
            try{
                while(rs.next()){
                tituloOriginal = rs.getString("tituloOriginal");
                tituloPortugues = rs.getString("tituloPortugues");
                classificacao = rs.getString("classificacao");
                sinopse = rs.getString("sinopse");
                duracao = rs.getString("duracao");
                ano = Integer.parseInt(rs.getString("ano"));
                System.out.println("tituloOriginal: " + tituloOriginal);
                System.out.println("tituloPortugues: " + tituloPortugues);
                System.out.println("classificacao: " + classificacao);
                System.out.println("sinopse: " + sinopse);
                System.out.println("duracao: " + duracao);
                System.out.println("ano: " + ano);
                comparator = true;}
            }
            catch(SQLException e){
                System.out.println("Exceção: " + e.toString());
            }
            if(comparator == true){
                new Filme(tituloOriginal, tituloPortugues, classificacao, sinopse, duracao, ano).setVisible(true);
                comparator = false;
            }else{
                System.out.println("Nenhum dado foi encontrado");
            }
            acessoBD.fechaConexao(); 
    }//GEN-LAST:event_Filme1ActionPerformed

    private void Filme2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filme2ActionPerformed
        int ano = 0, cod = 2;
            pedidoSQL1 = "SELECT * FROM filme WHERE codigo = '"+cod+"'";
            acessoBD = new AcessoBD();
            acessoBD.conecta();
            rs = acessoBD.consulta(pedidoSQL1);
            
            try{
                while(rs.next()){
                tituloOriginal = rs.getString("tituloOriginal");
                tituloPortugues = rs.getString("tituloPortugues");
                classificacao = rs.getString("classificacao");
                sinopse = rs.getString("sinopse");
                duracao = rs.getString("duracao");
                ano = Integer.parseInt(rs.getString("ano"));
                System.out.println("tituloOriginal: " + tituloOriginal);
                System.out.println("tituloPortugues: " + tituloPortugues);
                System.out.println("classificacao: " + classificacao);
                System.out.println("sinopse: " + sinopse);
                System.out.println("duracao: " + duracao);
                System.out.println("ano: " + ano);
                comparator = true;}
            }
            catch(SQLException e){
                System.out.println("Exceção: " + e.toString());
            }
            if(comparator == true){
                new Filme(tituloOriginal, tituloPortugues, classificacao, sinopse, duracao, ano).setVisible(true);
                comparator = false;
            }else{
                System.out.println("Nenhum dado foi encontrado");
            }
            acessoBD.fechaConexao();
    }//GEN-LAST:event_Filme2ActionPerformed

    private void Filme4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Filme4ActionPerformed
        int ano = 0, cod = 4;
            pedidoSQL1 = "SELECT * FROM filme WHERE codigo = '"+cod+"'";
            acessoBD = new AcessoBD();
            acessoBD.conecta();
            rs = acessoBD.consulta(pedidoSQL1);
            
            try{
                while(rs.next()){
                tituloOriginal = rs.getString("tituloOriginal");
                tituloPortugues = rs.getString("tituloPortugues");
                classificacao = rs.getString("classificacao");
                sinopse = rs.getString("sinopse");
                duracao = rs.getString("duracao");
                ano = Integer.parseInt(rs.getString("ano"));
                System.out.println("tituloOriginal: " + tituloOriginal);
                System.out.println("tituloPortugues: " + tituloPortugues);
                System.out.println("classificacao: " + classificacao);
                System.out.println("sinopse: " + sinopse);
                System.out.println("duracao: " + duracao);
                System.out.println("ano: " + ano);
                comparator = true;}
            }
            catch(SQLException e){
                System.out.println("Exceção: " + e.toString());
            }
            if(comparator == true){
                new Filme(tituloOriginal, tituloPortugues, classificacao, sinopse, duracao, ano).setVisible(true);
                comparator = false;
            }else{
                System.out.println("Nenhum dado foi encontrado");
            }
            acessoBD.fechaConexao();
    }//GEN-LAST:event_Filme4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gelaflix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gelaflix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gelaflix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gelaflix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCliente().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton Filme1;
    private javax.swing.JButton Filme2;
    private javax.swing.JButton Filme3;
    private javax.swing.JButton Filme4;
    private javax.swing.JButton Filme5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
